const boss = [
  {
    name: "Karen",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "https://i.imgur.com/LCOAcxa.png",
    fr: "Karen peut sembler un peu compliquée et chiante, mais elle est juste chiante ! /n Plus sérieusement, ce n'est pas un boss compliqué, il suffit que chacun remplisse son rôle et tout se passera bien. Premièrement en tant que healer, il faut absoluement éviter les aoes sinon vous allez vous faire endormir ! Pensez à débuff le Berserker dès qu'il se fera endormir pour être sûr qu'il soit prêt en cas de besoin. Une fois fait, vous pouvez débuff le Darkness Blade pour qu'il continue de faire la BP. /n Ensuite en tant que Darkness Blade, il faut s'occuper de le BP, mais aussi surveiller les Rams que Karen va invoquer, il y en a 3 différents, parmis ceux la, il faut en surveiller 2 qui rendent Karen immunisée aux dégats magiques. Le Darkness Blade doit les aggro et les attirer sur Karen, de manière à les tuer et faire la BP en même temps. Le troisième Ram (celui avec l'aura violette) sera pris par un DPS physique et enmené sur Karen. Maintenant en tant que Berserker, il faut faire attention aux aoes de Karen. Il y en a 2 différentes, on peut les différencier grâce aux effets visuels présent pendant que Karen fait son aoe. L'aoe avec des effets violets est le sleep, vous pouvez l'ignorer car le healer va vous débuff. Par contre, l'aoe avec des effets verts ne doit absolument pas être ignorée ! Si elle vous touche, vous recevez un debuff qui permettra a Karen de se soigner à chaque fois que vous la tapez. Il faudra donc la fear pendant qu'elle fait cette aoe, de manière à l'empêcher de la faire. /n Maintenant en Blade Master, il faudra faire la même chose que le Berserker, mais uniquement quand Karen sera immunisée au fear et qu'elle fait une aoe avec des effets verts. Vous pouvez aussi ignorer l'aoe avec les effets violet, puisque vous pouvez vous débuff seul. /n Et enfin en tant qu'Executionner, il vous suffit de taper le boss et de faire confiance à vos coéquipiers !",
    en: "Karen may look like a difficult and annoying boss, but that's not how it is. She is annoying, but fairly easy. Depending on your class you will need to pay attention to different things. /n First as a healer, you have to pay attention to the debuffs, and make sure you are not in Karen's aoes. If you are hit, you may fall asleep. Make sure to debuff the Berserker as fast as you can, so that he can do his job without any issue, once it's done, you can debuf the Darkness Blade. /n Now as the Darkness Blade, you have to pay attention to the rams that Karen will summons (the BP too). There's will be 3 different, you have to attack them exept the magic one (with a dark purple aura). If you don't do your job, your teammates can't deal any damage to Karen, and you will be stuck there forever. /n Now as the Berserker, you have to pay attentions to Karen's aoes. There are 2 different, you can tell them apart by the effects while she cast. The aoe with purple effects is the sleep, you can ignore this one, as the healer will debuff you. But the aoe with green effects will give a debuff to the players hit, and they will heal her with every hit. Your job would be to fear her when she cast this aoe, this way everyone can keep attacking. /n Now as the Blade Master, your job will be similar to the Berserker's job, you will ignore the sleep aoe, as you can debuff yourself. And when fear immunity is up, and Karen's is casting the green aoe, you will have to stun her, preventing her from healing. /n And now as the Executioner, you just have to hit and trust your mates.",
  },
  {
    name: "Quetzalcoatl",
    level: 100,
    location: "Tempest Ridge",
    soloable: true,
    img: "https://i.imgur.com/yFlkiIa.png",
    fr: "",
    en: "",
  },
  {
    name: "Sakuya",
    level: 115,
    location: "Abyss",
    soloable: false,
    img: "https://i.imgur.com/aIZ3LNh.png",
    fr: "",
    en: "",
  },
  {
    name: "Ferelwing",
    level: 115,
    location: "Abyss",
    soloable: false,
    img: "https://i.imgur.com/6Ns78un.png",
    fr: "",
    en: "",
  },
  {
    name: "Willow One-Eye",
    level: 115,
    location: "Abyss",
    soloable: false,
    img: "https://i.imgur.com/yHWACG2.png",
    fr: "",
    en: "",
  },
  {
    name: "Leonic",
    level: 115,
    location: "Abyss",
    soloable: false,
    img: "https://i.imgur.com/nKLxMaN.png",
    fr: "",
    en: "",
  },
  {
    name: "Esh-Ball",
    level: 115,
    location: "Abyss",
    soloable: false,
    img: "https://i.imgur.com/L2267sn.png",
    fr: "",
    en: "",
  },
  {
    name: "Phoenix",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "https://i.imgur.com/riYmGeM.png",
    fr: "Avant de s'attaquer à Phoenix, il est conseillé de tuer les monstres, puisqu'il applique un debuff qui vous retirera 50K HP à chaque fois que vous tapperez une cible. Ce debuff peut être retiré par le healer. /n Il a aussi une compétence qui fait beaucoup de dégats et peut être annulée si il est stun au bon moment, mais je vais devoir faire quelques runs pour vous donner plus d'infos. /n En ce qui concerne les CC, il est conseillé d'enchainer le fear et KD vers 50% hp.",
    en: "Before attacking Phoenix, it is advised to kill the monsters, as it applies a debuff that will remove 50K HP every time you hit a target. This debuff can be removed by the healer. /n It also has a skill that does a lot of damage and can be cancelled if it is stunned at the right time, but I will have to do some runs to give you more info. /n As for the CC, i'd advise you to fear and then KD at 50% hp.",
  },
  {
    name: "Alice",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "https://i.imgur.com/i3amF5Z.png",
    fr: "Alice est une boss plutôt simple, il faut détruire les cristaux autours d'elle, en détruisant le noir en dernier. /n Ensuite il suffit de la combattre, et de la CC à chaque fois qu'elle fera une AOE, l'ordre des CC est en général le suivant : Fear - stun - KD. /n Si vous mettez un peu de temps à la tuer, les cristaux risque de réapparaitre, il faudra alors les détruire rapidement, si le noir réapparait, détruisez le en priorité, car si il s'active tout le monde mourra. /n Alice appliquera régulièrement un debuff réduisant l'attaque de vos armes a 0. Il faudra que le healer vous le retire.",
    en: "Alice is a fairly easy boss, first destroy the crystals around her, starting with the red one and ending with the dark one. /n Then just fight her and CC her every time she cast an AOE, the order of CC is generally the following : Fear - stun - KD. /n If you take a bit too long to kill her, the crystals will reappear, you will need to destroy them quickly, if the dark one reappears, destroy it first, because if it's active everyone will die. She will regularly apply a debuff reducing your attack to 0. You will need to have the healer remove it.",
  },
  {
    name: "Nerokas",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "https://i.imgur.com/2cyt6By.png",
    fr: "Voici le boss le plus simple dans HoO d'après moi ! /n Pour faire simple, il n'y a rien en particulié à faire, il suffit de le frapper jusqu'à ce qu'il meurt. /n Pour le tuer plus rapidement, ils est conseillé de le fear, stun puis KD à partir de 50% hp.",
    en: "Here it is ! To me Nerokas is the easiest HoO boss. /n You don't need to do anything is particular, just hit until he dies. /n For faster kill, fear, stun and kd once the boss is 50% hp.",
  },
  {
    name: "Beryl",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "https://i.imgur.com/Q4EH300.png",
    fr: "Beryl est un boss un peu chiant, elle possède un renvoie, le genre de boss que personne n'aime. Mais il est possible de l'empêcher de faire ce renvoie, et je vais vous expliquer comment. /n Si votre groupe à un assez bon DPS, il faudra que votre Berserker la fear quand elle dira : 'Look at you, so strong...' pour la deuxième fois. Une fois fear, il est conseillé de la KD afin de la tomber le plus vite possible. Gardez le stun au cas ou elle ne meurt pas assez vite, et utilisez le quand elle placera une de ses mains au niveau de sa poitrine sans qu'il n'y ai d'AOE au sol. /n Si votre groupe à un DPS moyen, appliquez la même technique, mais conservez aussi le KD pour l'empecher de faire son renvoie.",
    en: "Beryl is one of those annoying bosses, as she got a reflect. But you can prevent her from doing it, and I'll explain how to do it. /n If your group has a good DPS, you should fear her when she says : 'Look at you, so strong...' for the second time. Once she is feared, it's recommended to have the BM KD her to kill her as fast as possible. Keep the stun up in case she doesn't die fast enough, and use it when she places one of her hands to her chest while standing still, without any AOE on the ground. /n If you feel like your pt DPS is a bit lacking, you should fear her when she says 'Look at you, so strong...' for the second time, and then keep the BM KD and stun up for the reflect animation.",
  },
  {
    name: "Phantom",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "https://i.imgur.com/WaIb1sz.png",
    fr: "Phantom peut invoquer 2 clones le rendant immunisé aux dégats. Pour l'en empêcher, il faut le CC (fear, stun , kd) vers 50% hp. /n Le Berserker et le Blade Master seront les rôles les plus importants sur ce boss, si ils ne remplissent pas leur rôle, vous ne pourrez pas tuer le boss ! /n En tant que Berserker : Il faut surveiller le chat et fear le boss lorsqu'il dira pour la deuxième fois : 'My mission ...', une fois fear, continuez à le taper et le fear à nouveau une fois l'immunité disparue. /n En tant que Blade Master : Gardez le stun et KD jusqu'à ce que l'immunité au fear apparaisse sur le boss, des que vous la voyez, il faudra le stun et le KD 4s. Si le boss ne meurt pas avant que l'immunité au stun ne disparaisse, il faudra le stun à nouveau. /n En tant que Heaker : Il faut surveiller les debuff des membres du groupe, car Phantom va de temps en temps en fear un. Il faudra le debuff aussi vite que possible. /n En cas d'échec, il faudra reset le boss et tuer les clones. Pour ce faire, l'a personne qui s'occupe de la BP devra passer en dps magique et tuer le clone de droite, puisqu'il renvoit les dégats physiques reçus. /n Pour rappel, si vous devez reset le boss, sachez qu'il n'y aura plus les messages pour indiquer quand le fear.",
    en: "Phantom can summon 2 clones that make him Immune to DMG, if not CC chained after below 50% hp properly. /n To prevent that, the Berserker and Blade Master have to chain CC the boss properly. /n As a Berserker : You have to pay attention to the chat and fear the boss when he will say 'my mission is ...' for the second time. Once you have feared him, stayed focused and fear again when the immunity goes away. /n As a Blade Master : You have to keep your KD and stun, and use them at the right time. Simply pay attention to the boss buffs, and when you see fear immunity, stun him and KD 4s as fast as you can. /n And now as a Healer : You have to pay attention to your teammates debuffs as the boss will periodically Fear them, you have to debuff as fast as you can ! /n Now if case you fail, reset the boss, and kill the clones. To do so the BP guy has to go Mdps to kill the one on the right as he reflects every Pdmg taken. /n As a reminder, as you reset the boss, you won't have the messages as an indicator anymore.",
  },
  {
    name: "Cale",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "https://i.imgur.com/BTPLJQV.png",
    fr: "Cale invoque un cristal qui l'immunise aux dégats physiques, et lui donne de l'attaque à chaque fois qu'il se fait taper. Il faut donc détruire le cristal aussi vite que possible et taper Cale le moins possible lorsque le cristal est là. /n Cale peut aussi fear avec une AOE, ce fear peut être débuff.",
    en: "Cale summons a crystal which makes him immune to physical DMG, and gives him more P-attack every time he is hit. You should destroy the crystal as fast as possible, and hit Cale as little as possible when the crystal is there. /n Cale can also fear with an AOE, which can be debuffed.",
  },
  {
    name: "Leo",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "",
    fr: "Leo fait partit des boss les plus simple de HoO, il ne fait rien en particulié avant 50% hp, et une fois a 50% hp il va lancer des AOE qui silence, mais il est possible de l'en empêcher, en enchainant les CC dès qu'il est à 50% hp. /n Pour la BP il est conseiller de demander à l'exe de passer en strike pour aider.",
    en: "Leo is one of the easiest bosses in HoO, he does nothing before 50% hp, and once he reaches 50% hp he will cast AOEs that silence, but you can prevent it by CCing him. /n For the BP it's recommended to ask the exe to go into strike to help.",
  },
  {
    name: "Dana",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "https://i.imgur.com/kI0pQ4u.png",
    fr: "Dana appliquera un debuff qui ressemble a une flame, ce debuff permettre de retirer the debuff 'Ice Coffin Root', il est donc conseillé de rester proche les un des autres de manière à ce que celui qui reçoit le debuff, puisse retirer le 'Ice Coffin Root'. /n Cependant, il est plus simple d'enchainer les CC à partir de 75% HP afin de l'empêcher d'utiliser son 'Ice Coffin Root'.",
    en: "Dana casts a flame 'debuff', this 'debuff' can be used to remove her Ice Coffin Root, it is generally optimal to have the team standing in close proximity so whoever has the flame debuff can remove the Root. /n However, it is easier to simply CC Chain her after 75% HP, so she doesn't cast the skill at all.",
  },
  {
    name: "Punishment",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "https://i.imgur.com/QrjX6YJ.png",
    fr: "Premièrement, il est conseillé de demander a l'Executioner du groupe de passer en strike pour aider avec la BP. /n Ensuite, quand Punishment fera spawn des tas de sable, il faudra que le Berserker les pousses histoire de limiter les dégats reçus. /n Il est conseiller le de fear, stun puis KD vers 50% HP. /n Si le boss n'est pas tuer assez vite, il est possible qu'il invoque des cristaux réduisant les dégats qu'il recevra.",
    en: "First, it is recommended to ask the Executioner to swap to a strike weapon for the BP. /n Then, when Punishment summons Volcano spots that deal dmg, the Berserker will have to push them to limit the damage it will receive. /n You should fear, stun, and KD to 50% HP. /n If the boss is not killed fast enough, it is possible that he will summon crystals that will reduce the damage he will receive.",
  },
  {
    name: "Crime",
    level: 115,
    location: "Haven Of Oblivion",
    short: "HoO",
    soloable: false,
    img: "",
    fr: "Crime se soignera de temps en temps, et s'appliquera par la même occasion un buff augmentant les dégats qu'il recevra pendant un court moment. /n Il possède un sort qui cause énormèment de dégats autours de lui, si il l'utilise, il est conseillé de reculer, afin de ne pas mourir. Mais il est aussi possible de l'en empêcher en le utilisant un stun/fear/kd à chaque fois qu'il lève les bras pour cast, sans qu'il n'y au d'AOE au sol.",
    en: "Crime uses self heal, that increases DMG Taken. /n He has a spell that deals massive damage around him, if he uses it, it is recommended to move back, to avoid dying. But it is also possible to prevent him by CCing him every time he raises his arms to cast, without any AOE on the ground.",
  },
];

export default boss;