const shop = [
  {
    img: "https://i.imgur.com/xuQfWwY.png",
    name: "Ultimate MP Potion Lv2",
    price: "20",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/uMgHn4O.png",
    name: "Nature's Call Potion Lv2",
    price: "20",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/487hufI.png",
    name: "Iron Skin Potion Lv2",
    price: "20",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/rnkzHIv.png",
    name: "Ultimate HP Potion Lv2",
    price: "20",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/zKyIUKc.png",
    name: "Swiftness Potion Lv2",
    price: "20",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/oolQVzJ.png",
    name: "All-Purpose Potion",
    price: "10",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/6K2pijs.png",
    name: "Tank Potion Lv2",
    price: "15",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/m1F3iDm.png",
    name: "War Potion Lv2",
    price: "15",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/WGdoTar.png",
    name: "Magician Potion Lv2",
    price: "12",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/sDerRGV.png",
    name: "Healer Potion Lv2",
    price: "12",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/4JNf0VX.png",
    name: "State Removal Potion Lv1",
    price: "9",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/1Kw2knz.png",
    name: "State Removal Potion Lv2",
    price: "20",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/YiOzZ6e.png",
    name: "Frozen In time Capsule",
    price: "10",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/KGJSdHi.png",
    name: "Poisonous Powder",
    price: "30",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/BIlMwNw.png",
    name: "Twist of Fate Tool",
    price: "15",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/69UuCPV.png",
    name: "Smoke Bomb",
    price: "15",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/MTwAJMu.png",
    name: "MP Little Sprite",
    price: "3000",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/kMJznVV.png",
    name: "HP Little Sprite",
    price: "3000",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/8qfRJGY.png",
    name: "Warrior Boots",
    price: "300",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/T6TFj2f.png",
    name: "TE - Warrior Lv2",
    price: "2700",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/6uFVRJo.png",
    name: "TE - Magical Guardian Lv2",
    price: "2700",
    seller: "0MaouSama0",
  },
  {
    img: "https://i.imgur.com/nmAGvdl.png",
    name: "TE - The Protector Lv2",
    price: "2700",
    seller: "0MaouSama0",
  },
];

export default shop;